# Site settings
title: AIMC2025 - Supplementary Demos
tag_text: AIMC2025
description: This page contains some videos of the AnonSystem operating under different stabilities
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
